### ISSUE TITLE
Bug with Saved Notes on phones

### ISSUE THREAD

**Issue by CyberL1** [supertiger1234/Nertivia-Client#106]
**Device + OS:**
Phone + Android

**Browser:**
Chrome (Pwa App)

**Bug:**
If you go to DMs and try to click Saved Notes, the friends drawner will not hide

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/6b97cc00d34434641c742e7af494bba11002672d 
Will be fixed after uploading. Thanks!
