### ISSUE TITLE
Invisible name

### ISSUE THREAD

**Issue by Jarsa132** [supertiger1234/Nertivia-Client#110]
**Device + OS:**
PC, Windows10

**Browser:**
Brave (im using desktop app)

**Bug:**
You can make invisible name using normal spaces
![image](https://user-images.githubusercontent.com/49820160/86119342-91c92b00-bad2-11ea-90b9-581505cbc3bc.png)
![image](https://user-images.githubusercontent.com/49820160/86119354-97bf0c00-bad2-11ea-8ef6-84e87b4aa79c.png)

**Comment by supertiger1234** [comment]
should already be fixed i think 😅 reopen if its not. thanks a lot!
