### ISSUE TITLE
Can't mention when sending image/file

### ISSUE THREAD

**Issue by Jarsa132** [supertiger1234/Nertivia-Client#111]
**Device + OS:**
PC, windows 10
**Browser:**
Brave (im using desktop app)

**Bug:**
When u sending a picture or file u can't mention 
![image](https://user-images.githubusercontent.com/49820160/86121951-39485c80-bad7-11ea-800a-2142ce483ad1.png)

**Comment by supertiger1234** [comment]
Fixed, thanks
