### ISSUE TITLE
Adding Thai (TH), German (DE), Finnish (FI) to Nertivia Client.

### ISSUE THREAD

**Issue by jsyreviews** [supertiger1234/Nertivia-Client#132]
I've gone ahead and translated both Thai and German accordingly, do note that my skill with those languages aren't perfect so expect some grammartical errors.

Had to zip the files since that's what Github supports.

[th and de.zip](https://github.com/supertiger1234/Nertivia-Client/files/4881461/th.and.de.zip)
- Misa:0001

**Comment by supertiger1234** [comment]
Thanks a lot for your effort!

**Comment by jsyreviews** [comment]
Jony (benis_benis:fEeK) had gone ahead and helped translating Finnish as well.

Here's the updated version of TH, DE and newly added FI.

Misa:0001

[Nertivia DE-TH-FI translations.zip](https://github.com/supertiger1234/Nertivia-Client/files/4884477/Nertivia.DE-TH-FI.translations.zip)

**Comment by supertiger1234** [comment]
Thanks a lot!!
