### ISSUE TITLE
Adding support for Slovenian (sl-SI) localization

### ISSUE THREAD

**Issue by shikikaze** [supertiger1234/Nertivia-Client#134]
I've gone ahead and translated what I could to Slovenian in my free time. Pretty fluent in English, however, there may be some terminology issues regarding the words "emoji" and such, for which I couldn't find a proper term for in Slovenian, so I just used slang.

The JSON: [sl.zip](https://github.com/supertiger1234/Nertivia-Client/files/4884122/sl.zip)

Best regards; Shik.

**Comment by supertiger1234** [comment]
Hey, did you upload the wrong file? it seems to be all in english

**Comment by shikikaze** [comment]
Shouldn't be... Uploading it again since it seems I screwed up...
[sl.zip](https://github.com/supertiger1234/Nertivia-Client/files/4890409/sl.zip)

**Comment by supertiger1234** [comment]
thats better 👌 
thanks, will be added in the next update
