### ISSUE TITLE
Contradicting file size limits

### ISSUE THREAD

**Issue by Secretowo** [supertiger1234/Nertivia-Client#148]
Not really a bug, but
under settings->manage emojis, it says:

> Upload your own pretty emojis for free! Emojis must be **3**MB or less. (png, jpg, gif)

Though when you try to upload an emoji that's too big, it says:

> Upload failed - Image size must be less than **1** megabytes.

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/6755e12c73bb0e1394954d1c9fe6b4763305aa5c
Fixed, Thanks! the emoji size should be 3MB or less
