### ISSUE TITLE
Desktop Notifications Bug

### ISSUE THREAD

**Issue by FiireWiinter** [supertiger1234/Nertivia-Client#155]
**Device + OS:**
Windows PC

**Browser:**
Desktop Client

**Bug:**
Desktop Notifications get sent, when "DND" mode is active

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/dd0c5ccf7b65644f98748cf8151e59acb181697c
Fixed hopefully. reload your app and if this issue still exists, reopen this issue pls
Thanks!
