### ISSUE TITLE
Buttons/Embeds don't work in DM's

### ISSUE THREAD

**Issue by anishanne** [supertiger1234/Nertivia-Client#157]
**Device + OS:**
All

**Browser:**
All

**Bug:**
Buttons/Embeds will not work in DM's, they have to be sent in a channel.

**Comment by supertiger1234** [comment]
Seems like i made a mistake: https://github.com/supertiger1234/nertivia.js/commit/583630c1a2348fea841afea9b225e677112136aa
Update your Nertivia.js `npm i nertivia.js@latest` and try again
Thanks!
