### ISSUE TITLE
Embed Preview doesn't show when you put text next to the embed.

### ISSUE THREAD

**Issue by anishanne** [supertiger1234/Nertivia-Client#161]
**Device + OS:**
All

**Browser:**
All

**Bug:**
If you post text next to a link in nertivia, embed doesn't show.
![image](https://user-images.githubusercontent.com/22670462/87340173-baf7ab80-c515-11ea-8da4-cbb7bd6e5e2c.png)

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Server/commit/f8d1cc2f8edd4bbf5a4d03c656a2d99ed3f2b574
Fixed, thanks
