### ISSUE TITLE
Bigger Management Page

### ISSUE THREAD

**Issue by anishanne** [supertiger1234/Nertivia-Client#163]
A bigger invite manager/server manager page. Currently, it takes up a very small portion of the page which is fairly annoying as everything becomes super cramped.

**Comment by supertiger1234** [comment]
made settings page bigger, going to work on server page some day.

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/e46c89569ffc176357f9ed9b02b9da54b46464b3 
Done, thanks and sorry for what happened between us.
