### ISSUE TITLE
Nick bug

### ISSUE THREAD

**Issue by 6Arin9** [supertiger1234/Nertivia-Client#169]
**Device + OS:**
PC, Windows

**Browser:**
Opera GX, Chrome

**Bug:**
No nickname by 4 spaces or more.
![Nertivia_YFrnX5uLT8](https://user-images.githubusercontent.com/67313390/87642746-3346b280-c74a-11ea-87b2-1f1efce11879.png)

**Comment by supertiger1234** [comment]
Thanks! should be fixed in the next update https://github.com/supertiger1234/Nertivia-Server/commit/c3af7f96bcb2ebb2ad695efbf321b626feae1010
