### ISSUE TITLE
Croatian translation (its here because idk how to make a pull request)

### ISSUE THREAD

**Issue by thekoneko** [supertiger1234/Nertivia-Client#174]
(i recommend calling this file hr.json)
{
    "explore": "Istraži",
    "explore-desc": "Nađi nove servere, emotikone i više!",
    "servers": "Serveri",
    "join-server": "Uđi u server",
    "themes": "Teme",
    "emoji-packs": "Emotikon pakovi",
    "message-styles": "Vrste poruka",
    "created-by": "Kreirao je",
    "filter": "Filter",
    "sort-by": "Posloži po",
    "all": "Sve",
    "verified": "Verificirani",
    "most-users": "Najviše korisnika",
    "least-users": "Najmanje korisnika",
    "alphabetical": "Abecednim redom",
    "date-added": "Datum dodano",
    "explore-support-message": "Podrži Nertivi-u tako da doniraš nešto novca. Dobiti češ 'podrživač' značku i više stvari u budučnosti.",
    "support-message-settings": "Podrži Nertivi-u. Dobiti češ značku.",
    "donate": "Doniraj",
    "join": "Uđi",
    "join-card-message": "Uđi u službeni Nertivia server",
    "coming-soon!": "Dolazi uskoro!",
    "joined": "Ušao je",
    "apply": "Primjeni",
    "unapply": "Vrati natrag",
    "copy-link": "Kopiraj link",
    "clone": "Kloniraj",
    "cloning": "Kloniranje...",
    "cloned": "Klonirano",
    "theme-safe-message": "Ove teme su sigurno pregledane.",
    "friends": "Prijatelji",
    "pending": "Pending",
    "recents": "Nedavni",
    "online": "Aktivan",
    "away": "Dalje",
    "busy": "Zaposlen",
    "looking-to-play": "Želi igrati",
    "offline": "Neaktivan",
    "add-friends-message": "Dodaj prijatelje.",
    "offline-message": "Svi tvoji prijatelji su neaktivni.",
    "saved-notes": "Spremljene bilješke",
    "select-person-message": "Odaberi osobu kojoj da pošalješ poruku!",
    "message": "Poruka",
    "add-server": "Dodaj server",
    "add-friend": "Dodaj prijatelja",
    "add-friend-message": "Dodaj prijatelje tako da koristiš njihovo korisničko ime i oznaku.",
    "adding": "Dodavanje...",
    "create": "Kreiraj",
    "new-messages": "Nove poruke",
    "today-at": "Danas u {0}",
    "yesterday-at": "Jučer u {0}",
    "send-a-message": "Pošalji poruku"
}

**Comment by supertiger1234** [comment]
Thanks a lot!
