### ISSUE TITLE
DMs server bar

### ISSUE THREAD

**Issue by ItsADerpyTurtle** [supertiger1234/Nertivia-Client#175]
**Device + OS:**
Laptop - Windows 10 Pro 64 bit

**Browser:**
Windows application - not web app

**Bug:**
After going to Direct Messages from a server, the white bar beside the server is still shown.

![image](https://user-images.githubusercontent.com/37308716/88223788-ee49e100-cc5f-11ea-84b1-9174c0782213.png)

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/12b151d2c7e82b4982459eaa075894faefef5a16
Thanks a lot! Will be fixed after uploading the build to the website.
