### ISSUE TITLE
If you create then delete a channel and don't refresh the client, you can still mention that deleted channel

### ISSUE THREAD

**Issue by CyberL1** [supertiger1234/Nertivia-Client#180]
**Device + OS:**
PC + Windows

**Browser:**
Native Desktop App

**Steps to reproduce:**
1. Create a channel
2. Delete it
3. Try to mention it

**Excepted behavior:**
You cannot mention the channel

**Actual behavior:**
You can still mention the channel
![image](https://user-images.githubusercontent.com/44707958/88299492-b647aa00-cd02-11ea-85ed-df4849124f14.png)

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/86c2a79a15136c48aa02635e1282462b0a18b294

Fixed, thanks! Will be uploaded soon.
