### ISSUE TITLE
Channel Sections/Status Colors

### ISSUE THREAD

**Issue by vw3i** [supertiger1234/Nertivia-Client#192]
Self explanatory, Would like to see Channel Sections (Something Like Discord)  🙂 

For the status colors it would be something like discord's but a round ring around the profile picture or something like that to match Nertivia's Style. (Same for the bot's js api 😉)

**Comment by supertiger1234** [comment]
Not sure what you mean by status colors. Nertivia does have a status color around the background?

**Comment by vw3i** [comment]
oh I guess I just couldn't see it lol. but yeh otherwise I'd like to see channel sections and moving channels around ;P

**Comment by supertiger1234** [comment]
Ahh alright, will add the channel selection category thing some day, thanks! 😃

**Comment by Brecert** [comment]
Because these are two separate ideas and one of them was solved, I'll be closing this for now.

For channel sections/categories related discussion please use #201 for now.
