### ISSUE TITLE
cant build nertivia

### ISSUE THREAD

**Issue by GramingFoxTeam** [supertiger1234/Nertivia-Client#196]
**Device + OS:**
Windows 10

**Bug:**
I think this is related to vue but here it is:

When i try to build Nertivia, it fails

 ERROR  Failed to compile with 38 errors                                                                                                  12:30:59

These dependencies were not found:

* @/config in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/app/ServerList.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/app/Popouts/Popouts/ServerSettingsPanels/ManageBans.vue?vue&type=script&lang=js& and 5 others
* @/config.js in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/app/MainNav.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/app/Navigation.vue?vue&type=script&lang=js& and 14 others

To install them, you can run: npm install --save @/config @/config.js

These relative modules were not found:

* ../../config in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/app/InviteMessage.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/app/ThemeMessage.vue?vue&type=script&lang=js&
* ../config in ./src/services/Api.js
* ../config.js in ./src/services/ServerService.js, ./src/services/settingsService.js and 9 others
* ./config.js in ./src/router.js

and yes, i tried doing npm install --save @/config @/config.js but it fails too.

Edit:I tried TS version and it worked with no problem

**Comment by toman222** [comment]
You''re missing the config file

**Comment by GramingFoxTeam** [comment]
> You''re missing the config file
is there any example of it? (config.json)

**Comment by toman222** [comment]
#71

**Comment by GramingFoxTeam** [comment]
Ah, welp.

**Comment by Brecert** [comment]
Because this issue is essentially #71 I'll be closing this. Any further discussion about `config.js` should be directed there.
