### ISSUE TITLE
popups have an annoying animation

### ISSUE THREAD

**Issue by Kreyren** [supertiger1234/Nertivia-Client#22]
Popups have an annoying animation if you hover on anything that has popup and then hover on something else that has popup then the popup moves across the whole screen.

**Comment by supertiger1234** [comment]
You can make a themes in Nertivia if you don't like that feature. A lot of people like that animation :D

**Comment by Kreyren** [comment]
meh it would be nice to have some toggle for this instead

**Comment by supertiger1234** [comment]
It's only you that doesn't like it. You can make a theme in Nertivia and fix that.

Thanks though!
