### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by JarDidi** [supertiger1234/Nertivia-Client#227]
**Device + OS:**
Windows 10 PC

**Browser:**
Chrome

**Bug:**
When trying to login and doing the hCaptcha it gives the check mark like I did it right but then doesn't log me in

**Comment by toman222** [comment]
from personal experience:
Click on the links inside the hCaptcha, then somewhere around it, and it usually works for some reason

**Comment by supertiger1234** [comment]
Server was getting ddosed at that point. I added rate limit so hopefully this doesn't happen again.
