### ISSUE TITLE
False Icons

### ISSUE THREAD

**Issue by zian-zian** [supertiger1234/Nertivia-Client#237]
**Safari of iPhone 8 on iOS 14:**

I was just scrolling through Nitervia and I see the edit icon beside a message sent by someone else. I tried clicking on it and luckily, it does nothing, but it is not meant to be there.

![image](https://user-images.githubusercontent.com/72253494/94919562-40707380-04e7-11eb-8da7-b197b4c569fd.jpeg)

**Comment by JasonTheKitten** [comment]
This icon indicates that a message *has* been edited, not that you can edit it

**Comment by MadMatix** [comment]
yeah

**Comment by zian-zian** [comment]
Sorry, didn't know that. Thanks!
