### ISSUE TITLE
Empty username

### ISSUE THREAD

**Issue by MadMatix** [supertiger1234/Nertivia-Client#240]
**Device + OS:**
Global Bug

**Browser:**
Global Bug

**Bug:**
User can use empty UNICODE symbols to get empty username. (UNICODE list for example: https://unicode-table.com/pl/#2061)
![image](https://user-images.githubusercontent.com/42451085/94944133-1748e680-04d9-11eb-86cf-43edb5529caf.png)

**Comment by supertiger1234** [comment]
While this can be impossible to fix, I have filtered out some unicodes so this should prevent this from happening in the future.https://github.com/supertiger1234/Nertivia-Server/commit/621d6fef6f3e473e5e0f0a10cc9f41b8c46a60ed
thanks!
