### ISSUE TITLE
Login with username

### ISSUE THREAD

**Issue by 9inpachi** [supertiger1234/Nertivia-Client#25]
Don't know if it's planned but allowing users to log in with their username would be cool.

**Comment by supertiger1234** [comment]
This is not possible due to multiple people having the same username with different tags

**Comment by 9inpachi** [comment]
I consider the tag to be part of the "username" I am talking about.
Since the tags can be changed too so I think it makes sense.

**Comment by supertiger1234** [comment]
Ohh, I see. That could be added. Ill maybe add this next :D

**Comment by 9inpachi** [comment]
Great. Close the issue when you do. xD

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/f29e594895ed6718d61e59c478e20cca9fc5ed7f#diff-9cf42dea3a62c7f9e009e9d55207989f https://github.com/supertiger1234/Nertivia-Server/commit/3a473e0e21ab8ef05f5078ee0f0b032c861af12f
