### ISSUE TITLE
Italic markup parsing stops at _ instead of /

### ISSUE THREAD

**Issue by Brecert** [supertiger1234/Nertivia-Client#254]
**Device + OS:**
Windows 10

**Browser:**
Firefox 81.0

**Bug:**
When formatting italic in markup, it stops at the first `_` found rather than `/`
see the regex at: https://github.com/supertiger1234/Nertivia-Client/blob/master/src/components/app/Markup.vue#L35

**Comment by skspuddd** [comment]
I think this is the issue I fixed, feel free to close this?

**Comment by Brecert** [comment]
Fixed in #270
