### ISSUE TITLE
Nertivia doesn't load up on Internet Explorer

### ISSUE THREAD

**Issue by 9inpachi** [supertiger1234/Nertivia-Client#27]
I know this is the last thing someone would do but still xD

Nertivia doesn't load up on Internet Explorer. And I think it doesn't need to since it uses a lot of modern JavaScript and CSS.

However, it would be cool to have a message showing that deprecated browsers aren't supported.

**Comment by 9inpachi** [comment]
![image](https://user-images.githubusercontent.com/36920441/78067115-9a18a980-73af-11ea-997d-7cc3743f2301.png)

**Comment by supertiger1234** [comment]
Should be easy maybe, by checking what browser it is via js

**Comment by dvhe** [comment]
Vue doesn't support IE out of the box anymore, because of the way some things are handled internally, the only solution to this would be to downgrade to a older version of vue or add a lot of things to your project to support it

**Comment by supertiger1234** [comment]
But I'm sure its possible to show an message that says that It is unsupported?

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/dda41deb1b2d58638084be3e0221981076585342
