### ISSUE TITLE
Don't "merge" messages that have a difference of more than 7 minutes in time

### ISSUE THREAD

**Issue by chris9740** [supertiger1234/Nertivia-Client#277]
If I send a message at 10:00 am, and then another one at 1:00pm the next day, those two messages get merged together, making it seem like they were sent at the same time. By merge, I mean that they are right under each other. If there is a difference of more than 7 minutes, the next message should be in a new "group," much like how Discord does it

**Comment by supertiger1234** [comment]
That is already a thing in nertivia beta, but thanks! I dont work on the current version of nertivia since i am recreating nertivia at https://beta.nertivia.net
