### ISSUE TITLE
You can put an empty space in role name

### ISSUE THREAD

**Issue by CyberL1** [supertiger1234/Nertivia-Client#282]
**Device + OS:**
PC + Windows 10

**Browser:**
Nertivia Desktop App

**Bug:**
You can put an empty space in role name
![image](https://user-images.githubusercontent.com/44707958/104131617-a63a8a00-5377-11eb-9ff8-04bc02180caa.png)

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Server/commit/e78ab26d21c0fa4e2b0594679dc9832fec5d6604
fixed, uploading.

thanks!
