### ISSUE TITLE
Double links do not linkify

### ISSUE THREAD

**Issue by Brecert** [supertiger1234/Nertivia-Client#29]
When more than one link is posted in sequence, the second link will not linkify.
![image](https://user-images.githubusercontent.com/11599528/78073353-bcd69e00-736e-11ea-89e7-95faf1cff1b8.png)

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/b82d497d239cf890e71924b432c3f4bc9c941ba6
