### ISSUE TITLE
Bug Avatar

### ISSUE THREAD

**Issue by Bugzinnsz** [supertiger1234/Nertivia-Client#35]
_There is a bug in changing the avatar...
When avatar changed, the avatar is not changed in the members sidebar, only after restarting the app_

**Comment by supertiger1234** [comment]
Thanks a lot. I'll see what I can do.

**Comment by Bugzinnsz** [comment]
> 
> 
> Thanks a lot. I'll see what I can do.

:D

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/48f394458ef479f71b34836dd9e94ae03e742f69

Thanks a lot, this should be fixed in production soon.
