### ISSUE TITLE
Bug new members

### ISSUE THREAD

**Issue by Bugzinnsz** [supertiger1234/Nertivia-Client#36]
_New members of the server when they enter remain with the default color, not the one determined for the tag_

**Comment by supertiger1234** [comment]
i dont understand what you mean

**Comment by Bugzinnsz** [comment]
> 
> 
> i dont understand what you mean

New members of the server do not get the color determined for the tag they get the default

**Comment by supertiger1234** [comment]
Can you show a video of the issue please, I still don't understand. I tested it myself but it seems to work fine.

**Comment by Bugzinnsz** [comment]
> 
> 
> Can you show a video of the issue please, I still don't understand. I tested it myself but it seems to work fine.

I'm sending in your DM

**Comment by supertiger1234** [comment]
I think you got mistaken. the colored outlines are your online status. If you still think something is wrong, reopen this issue.

Thanks!
