### ISSUE TITLE
Mention channels

### ISSUE THREAD

**Issue by FluxedScript** [supertiger1234/Nertivia-Client#39]
Mention a channel using #general and it will create a link when clicked direct the user to that channel.

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/71b17279001e4cdd678948402dd0f2ff08385535
https://github.com/supertiger1234/Nertivia-Client/commit/44618f63593fa2e267946f86b74e5f71c061e461
