### ISSUE TITLE
User account pins

### ISSUE THREAD

**Issue by FluxedScript** [supertiger1234/Nertivia-Client#41]
Like Windows 10 you can remember a small pin to replace password login. Like 42814 instead of iReallyDontknowPasswords!?

**Comment by Brecert** [comment]
It's functionally the same (and less secure) as a normal password.

**Comment by supertiger1234** [comment]
Indeed, I'm closing this issue

**Comment by FluxedScript** [comment]
> Indeed, I'm closing this issue

What about a security pin for your account so if you forget your password you can use it. You can use it also for account settings like deleting when you implement that
