### ISSUE TITLE
Bot users

### ISSUE THREAD

**Issue by FluxedScript** [supertiger1234/Nertivia-Client#42]
If you create bot users. Other users can invite them to servers. This is good as currently it's hard to know who is a bot and who is not. Then on the discovery page where you find servers you can have a bots page verified and unverified. Then filter by server count the bot is in.

**Comment by Brecert** [comment]
I believe this was added in https://github.com/supertiger1234/Nertivia-Client/commit/240934b05db5237c3ac38fd21f70d13a16225e99

Although the explore page for bots hasn't been added.

**Comment by Brecert** [comment]
#90 should be used for any thoughts on an explore page for bots.
