### ISSUE TITLE
Status's

### ISSUE THREAD

**Issue by JarDidi** [supertiger1234/Nertivia-Client#50]
Don't allow text markdown in status as well as set a character limit, will prevent this kind of thing
[Example Here](https://media.discordapp.net/attachments/368474823636025347/697976328212840508/unknown.png)

**Comment by Brecert** [comment]
Rather than removing all markdown, limiting it to only certain (mostly inline) formatting might be a better option.

**Comment by Brecert** [comment]
The ability to control this was added in 2e88ae680e7983bc16b9b594079d4e7317fb42fb, and was used shortly afterwards.
If there's any markup components that should be disabled that aren't currently, please open a new issue.
