### ISSUE TITLE
Manage Emojis bug

### ISSUE THREAD

**Issue by DerpyWolfie** [supertiger1234/Nertivia-Client#55]
You can use the same name for every emoji when you write down for example, other emojis doesn't want to work.
![bug1](https://user-images.githubusercontent.com/63740145/79365649-2fd53c80-7f4b-11ea-93cc-383952848789.png)
![bug2](https://user-images.githubusercontent.com/63740145/79365650-306dd300-7f4b-11ea-9377-f542c5766058.png)
![bug3](https://user-images.githubusercontent.com/63740145/79365652-306dd300-7f4b-11ea-8a18-85400c7773bc.png)

**Comment by supertiger1234** [comment]
Should be an easy fix. I'll fix it after I'm done with the Nertivia CDN. Thanks!

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/6956a5cb3eb2f6665a38e9678dc180a5dd5f83ad

Fixed, thanks a lot for reporting bugs!
