### ISSUE TITLE
[suggestion] Keyboard shortcuts

### ISSUE THREAD

**Issue by piratehacker** [supertiger1234/Nertivia-Client#57]
I'd like to have some shortcuts that are on discord, like:
ctrl+e - open emoji picker
alt+up/down arrow - switch channels
ctrl+alt+up/down arrow - switch servers

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/c2f49debe35dd8164536e7ef1a34394a9cbebe54
Done! Thanks a lot for helping out on this project :)
