### ISSUE TITLE
FIX THE MISSIZE OF THE THINGY WHICH IS SEVRER

### ISSUE THREAD

**Issue by UmbreonFR4** [supertiger1234/Nertivia-Client#61]
FIX THE MISSIZE OF THE THINGY WHICH IS SEVRERFIX THE MISSIZE OF THE THINGY WHICH IS SEVRERFIX THE MISSIZE OF THE THINGY WHICH IS SEVRER

**Comment by supertiger1234** [comment]
K FIXED https://github.com/supertiger1234/Nertivia-Client/commit/94dfa171ef65bdb1dba59400f805b3f294f4d8ca

THX BYE
