### ISSUE TITLE
Add a data attribute for the selected server to the .direct-message-tab div

### ISSUE THREAD

**Issue by atomic-addison** [supertiger1234/Nertivia-Client#64]
Would be really cool if you could add a data attribute with the name of the selected server in the .direct-message-tab div, for example data-server="nertivia". It would let themes hook a pseudo element to the container with the server name.

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/f3b9d2c8a7e54d4b080b8913884a66121cca4584

👌 ty
