### ISSUE TITLE
Emojis on attachment modal

### ISSUE THREAD

**Issue by CyberL1** [supertiger1234/Nertivia-Client#66]
Can you please add emoji picker on attachment modal? I mean if i typed the `:` and then the emoji name, the chooser doesn't show up, like there
![image](https://user-images.githubusercontent.com/44707958/80715173-47d5c000-8af6-11ea-85e2-b14317cf4d7d.png)

**Comment by Brecert** [comment]
Could you clarify what you mean by the "attachment modal"?

**Comment by Brecert** [comment]
Apparently Cyber has clarified that this has already been changed.
