### ISSUE TITLE
Plees Pro lit Fam M4ke da Thinoy ()F load1ng Ze Usor InFos Be InviSIble

### ISSUE THREAD

**Issue by UmbreonFR4** [supertiger1234/Nertivia-Client#74]
Plees Pro Lit f4m M4ke da Thinoy ()F load1ng Ze Usor InFos Be InviSIble

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/50eb8c8cfa0dee0acefb0ab80ecf1f250c3d108a ez donethx
