### ISSUE TITLE
mention issue.

### ISSUE THREAD

**Issue by ViperLands** [supertiger1234/Nertivia-Client#75]
when you try to mention a user on a server it work as expected but
doesnt want to mention when you try to mention in DM.
by lufi fr:ProV

**Comment by supertiger1234** [comment]
https://github.com/supertiger1234/Nertivia-Client/commit/25e938715e8de7ee9da9851196f98aa1ec281c0a Thanks for helping me improve Nertivia :) This feature has been added.
