### ISSUE TITLE
Channel Muting

### ISSUE THREAD

**Issue by Yaekith** [supertiger1234/Nertivia-Client#79]
**Device + OS:**
Windows

**Browser:**
Google Chrome

**Bug:**
You can actually mute a channel more than once, you can reproduce this by sending the request for muting the select channel more than once, it will go through and not even give a response of "Channel is already muted.", It will just respond back with an A-OK Response of it been muted even though it's already muted!!

**Comment by Yaekith** [comment]
So angery >:(

**Comment by supertiger1234** [comment]
added checks :D https://github.com/supertiger1234/Nertivia-Server/commit/c2642f4c5245e68ab8bd4f1622f8a464e3f79e1a
