### ISSUE TITLE
Upload emotes in archive files

### ISSUE THREAD

**Issue by CyberL1** [supertiger1234/Nertivia-Client#97]
Please allow us to upload emotes in archive files, cuz if you want to add e.g. 10 emotes, you have to do it one by one for now

**Comment by Indexerrowaty** [comment]
Great idea

**Comment by supertiger1234** [comment]
Thanks for this great idea! Implimented. https://github.com/supertiger1234/Nertivia-Client/commit/ca2f8d08e2e900665fabda7e508e82e39438d377
